[package]
name = "ldk-tutorial-node"
version = "0.1.0"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning = "0.0.14"
lightning-block-sync = { version = "0.0.14", features = [ "rpc-client" ] }
lightning-invoice = "0.5"
lightning-net-tokio = "0.0.14"
lightning-persister = "0.0.14"
lightning-background-processor = "0.0.14"

base64 = "0.13.0"
bitcoin = "0.26"
bitcoin-bech32 = "0.7"
bech32 = "0.7"
hex = "0.3"

futures = "0.3"
time = "0.2"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1.0", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
